name: Load Data from UNECE
on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/load-unece-data.yml
      - queries/**
      - schema/**
  schedule:
    - cron: 25 7 5 * *
jobs:
  load:
    name: Load Data
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: rust
        name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - id: htmlq
        name: Install htmlq
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: htmlq
      - id: dolt
        name: Install Dolt
        uses: sebhoss/dolt-installer@v1
      - id: htmlq_verify
        name: Verify htmlq
        run: htmlq --version
      - id: dolt_verify
        name: Verify Dolt
        run: dolt version
      - id: dolthub_jwk
        name: Run Workflow
        uses: timheuer/base64-to-file@v1.1
        with:
          encodedString: ${{ secrets.DOLTHUB_JWK_BASE64 }}
      - id: dolt_creds
        name: Import Dolthub Credentials
        run: dolt creds import ${{ steps.dolthub_jwk.outputs.filePath }}
      - id: dolt_clone
        name: Clone Dolt Data
        run: dolt clone sebhoss/countries-and-cities .
      - id: dolt_migrate
        name: Migrate to new Database Format
        run: dolt migrate
      - id: import_data
        name: Import UNECE Data
        run: make import
      - id: dolt_diff
        name: Show Data Diff
        run: dolt diff
