name: Load Data from UNECE
on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/load-unece-data.yml
      - queries/**
      - schema/**
  schedule:
    - cron: 25 7 5 * *
jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: rust
        name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - id: htmlq
        name: Install htmlq
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: htmlq
      - id: dolt
        name: Install Dolt
        uses: sebhoss/dolt-installer@v1
      - id: countries
        name: Load Countries
        run: make work/LoadHubCountryStaging.sql
